---
output:
  html_document:
    fig_width: 1
---

----

Hi! I'm Emily Malcolm-White and I am an experienced educator and student support specialist with experience developing and teaching mathematics, statistics, and data science courses. 

I believe that STEM education should be inclusive and accessible for all. I hope to minimize barriers for all students, including those with varying academic backgrounds, those with responsibilities outside of academics, and those with disabilities. I take the time to learn about innovative and effective teaching pedagogy, I use innovative new technology in and out of the classroom, and like to keep trying new things to maximize my effectiveness as an instructor. 

I currently work as a Lecturer in Mathematics and Statistics at Middlebury College in Vermont. Prior to that I was a Math and Statistics Specialist within the Academic Assistance and Tutoring Centers at UC Davis. I have a BSc in Applied Mathematics and Statistics from the University of Guelph and a MSc in Statistics from the University of Victoria. 